leftnav:
- identifier: dbb218cd-6c1a-eb61-9614-d4b02ef33b68
  name: Syllabus
  pageRef: /pages/syllabus
  weight: 10
- identifier: 94352e35-98de-71c5-5378-6ea9386d6b41
  name: Calendar
  pageRef: /pages/calendar
  weight: 20
- identifier: 5029b0ef-1d33-4706-adfa-3224d6c77146
  name: Readings
  pageRef: /pages/readings
  weight: 30
- identifier: 62730290-4197-c77e-e68d-d1a5d37684f5
  name: Projects
  pageRef: /pages/projects
  weight: 40
